### ISSUE TITLE
How to getting weather (Fitable API in our case)

### ISSUE THREAD

**Issue by minwoojeon** [SemicolonJungwon/jsOxygen#4]
- https://www.youtube.com/watch?v=FZakfROdxU0
When Chapter 14. Getting Weather in - 'https://openweathermap.org' site - . 
I hope to use this site. But before that, I want to hear each other's opinions. 

## Who will be responsible for the API portion? 

There is still lot of time to think about it. :)

**Comment by AreyouHappy** [comment]
Jung-won takes responsibility unconditionally.
